spring:
  config:
    activate:
      on-profile: prod

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}

management:
  endpoint:
    health:
      show-details: never
