spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: never
